### ISSUE TITLE
Documentation Issue - URL

### ISSUE THREAD

**Issue by zswalker** [CSC-256-Group-Project-9/Group-9-Postman-Lab#2]
This documentation issue for the document Lab How to use GET.

The update URL is not posted in the directions.

I have provided a screenshot for reference.
![image](https://github.com/CSC-256-Group-Project-9/Group-9-Postman-Lab/assets/103614234/7495c246-5c41-4434-ba05-275c43f0b74e)

Additional Note: It may not be a bad idea to move the opening bracket "{" to a new line to help prevent copy and paste errors.

**Comment by StefanESlaczka** [comment]
Will make a pull request on it

**Comment by zswalker** [comment]
Opening bracket issue resolved.

**Comment by zswalker** [comment]
Link has been added to the document.
